/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feuxdecroisement;
 import java.awt.Image;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.JComponent;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author youmzeyna
 */
public class FeuDeCroisement extends javax.swing.JFrame {

    /**
     * Creates new form FeuDeCroisement
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Image image = ImageIO.read(new File("resource/FEUvert.jpg"));
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        jLabel2.setText("jLabel2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
public void Etat1(){
    ImageIcon img = new ImageIcon("resource/FEUOrange.jpg"); //full path of image
        Image img2 = img.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),1);
        ImageIcon img3 = new ImageIcon(img2);
        jLabel1.setIcon(img3);
        
        ImageIcon image = new ImageIcon("resource/voiture.gif"); //full path of image
        Image image2 = image.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),1);
        ImageIcon image3 = new ImageIcon(image2);
        jLabel2.setIcon(image3);
        
        ImageIcon imagee = new ImageIcon("resource/piéton1.gif"); //full path of image
        Image imagee4 = imagee.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),1);
        ImageIcon imagee5 = new ImageIcon(imagee4);
        jLabel3.setIcon(imagee5);
        
       /* ImageIcon imageeA = new ImageIcon("resource/goudron11.jpg"); //full path of image
        Image imageeA5 = imageeA.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(),1);
        ImageIcon imageeA6= new ImageIcon(imageeA5);
        jLabel4.setIcon(imageeA6);*/
}

public void Etat2(){
    ImageIcon img = new ImageIcon("resource/FEUvert.jpg"); //full path of image
        Image img2 = img.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),1);
        ImageIcon img3 = new ImageIcon(img2);
        jLabel1.setIcon(img3);
        
        ImageIcon image = new ImageIcon("resource/voiture.gif"); //full path of image
        Image image2 = image.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),1);
        ImageIcon image3 = new ImageIcon(image2);
        jLabel2.setIcon(image3);
        
        ImageIcon imagee = new ImageIcon("resource/piétionp.jpg"); //full path of image
        Image imagee4 = imagee.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),1);
        ImageIcon imagee5 = new ImageIcon(imagee4);
        jLabel3.setIcon(imagee5);
        
        
        /*ImageIcon imageeA = new ImageIcon("resource/route.jpg"); //full path of image
        Image imageeA5 = imageeA.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(),1);
        ImageIcon imageeA6= new ImageIcon(imageeA5);
        jLabel4.setIcon(imageeA6);*/
}

public void Etat3(){
    ImageIcon img = new ImageIcon("resource/FeuRouge.jpg"); //full path of image
        Image img2 = img.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),1);
        ImageIcon img3 = new ImageIcon(img2);
        jLabel1.setIcon(img3);
        
        ImageIcon image = new ImageIcon("resource/voiture1.jpg"); //full path of image
        Image image2 = image.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),1);
        ImageIcon image3 = new ImageIcon(image2);
        jLabel2.setIcon(image3);
        
        ImageIcon imagee = new ImageIcon("resource/piéton1.gif"); //full path of image
        Image imagee4 = imagee.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),1);
        ImageIcon imagee5 = new ImageIcon(imagee4);
        jLabel3.setIcon(imagee5);
        
}

public FeuDeCroisement()   {
       initComponents(); 
       
       Etat3();
       
    Timer chrono = new Timer();
    
    chrono.schedule(new TimerTask() {
        
           @Override
           
           public void run() { 
               
               Etat2();
               
               Timer chronoo=new Timer();
               chronoo.schedule(new TimerTask() {
                   
                   @Override
                   
                   public void run() {
                       Etat1();
                       
                       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                   }
               }, 2500);
           
               
               throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           }
       }, 2500);
   
      
      
       
   
       
 
        }



 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeuDeCroisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeuDeCroisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeuDeCroisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeuDeCroisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
              // Panel panel= new Panel();
               // accueil acc =new accueil();
         
                FeuDeCroisement feu =new FeuDeCroisement();
                
                //acc.getContentPane().add(panel);
               // feu.add(acc);
                // feu.getContentPane().add(panel);
                feu.setVisible(true);
                 
                 
                
            }
        });
}
}
